### PR TITLE
rephrase authorization server confirmation section

### PR DESCRIPTION
**Pull request by aaronpk**

### CODE REVIEW

**Comment by sknebel** [comment]
this sounds a bit as if you need to implement both paths, I'd prefer it to be clearer that the first case is an optimization (since depending on tooling used, recording each individual step can be surprisingly tricky)

**Review by Zegnat — APPROVED** [review]

**Review by sknebel — APPROVED** [review]

**Review by sknebel — APPROVED** [review]

**Review by Zegnat — CHANGES_REQUESTED** [review]
Just realised: I think we want to add this new section to the top of the [Authorization](https://indieauth.spec.indieweb.org/#authorization) section. Both as part of the flow diagram and the written list below it.

**Comment by aaronpk** [comment]
I think I'm going to add a step to the flow diagram with an arrow from client to user URL, even though that fetch might be skipped in some cases

**Review by Zegnat — APPROVED** [review]
Flow diagram and up-top step list looks good to me!

**Pull request merged**
